name: Levels deploy Cubi

on:
  push:
    branches:
      - Cubi_3

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync files
        run: |
          aws s3 cp ./summary.json s3://cubi.levels.i4k/summary.json
          aws s3 sync --follow-symlinks --delete ./Level s3://cubi.levels.i4k/Level
          aws s3 sync --follow-symlinks --delete ./Solution s3://cubi.levels.i4k/Solution

      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID_CUBI }} --paths "/*"
