name: Upgrade levels

on: 
  project_card:
    types: [moved]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Upgrade level files
      run:
        python upgrader.py
